const refs = {
  body: document.querySelector('body'),
  trendMovies: document.querySelector('.gallery-list'),
  inputMovies: document.querySelector('#header__form'),
  searchProblemAlarm: document.querySelector('.form__text'),
  container: document.querySelector('#pagination'),
  watchedBtn: document.querySelector('.header-button-watched'),
  queueBtn: document.querySelector('.header-button-queue'),
  homeLink: document.querySelector('.js-home'),
  libraryLink: document.querySelector('.js-library'),
  inputLink: document.querySelector('.js-input'),
  buttonsLink: document.querySelector('.js-buttons'),
  headerLink: document.querySelector('.header__container'),
  outputRefs: document.querySelector('.media-container'),
  headerRefs: document.querySelector('.header'),
  logoTextRefs: document.querySelector('.logo__text'),
  paginationRefs: document.querySelector('.pagination'),
  footerModalLink: document.querySelector('.footer-link'),
  watched: document.querySelector('#watched'),
  queue: document.querySelector('#queue-list'),
  libraryBtns: document.querySelector('.header__container'),
  tuiBtn: document.querySelector('.tui-page-btn'),
  modalBackdrop: document.querySelector('.backdrop'),
  modalContent: document.querySelector('.modal__content'),
  modalBtnClose: document.querySelector('.modal__close'),
};

export default refs;
